TastyNet/TastyNet/Controllers/RecipesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Text;
using System.Text.Json;

namespace TastyNet.Controllers
{
    public class RecipesController : Controller
    {

        // Quick & Easy
        public IActionResult ThirtyMinuteMeals() => View();

        public IActionResult FiveIngredientsOrLess() => View();

        public IActionResult OnePotDishes() => View();

        // Comfort Food
        public IActionResult CasserolesAndBakes() => View();

        public IActionResult SoupsAndStews() => View();

        public IActionResult FamilyFavorites() => View();

        // World Flavors
        public IActionResult Italian() => View();

        public IActionResult Asian() => View();

        public IActionResult Mexican() => View();

        // Cakes & Cupcakes
        public IActionResult CakesAndCupcakes() => View();

        public IActionResult CookiesAndBars() => View();

        public IActionResult PiesAndDesserts() => View();

        // Healthy Choices
        public IActionResult LowCarb() => View();

        public IActionResult VeganAndVegetarian() => View();

        public IActionResult GlutenFree() => View();

        // Weekend Meals
        public IActionResult RoastsAndGrills() => View();

        public IActionResult BrunchFavorites() => View();

        public IActionResult PartyPlates() => View();

    }
   
}

TastyNet/TastyNet/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using System.Net.Http.Headers;
using System.Text.Json;
using TastyNet.Models;
using TastyNet.Servicios;
using static System.Net.Mime.MediaTypeNames;
using static System.Net.WebRequestMethods;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using System.Reflection;
using TastyNet.Services;
using Newtonsoft.Json.Linq;

namespace TastyNet.Controllers
{
    [Authorize(Roles = "2")]
    public class UserController : Controller
    {
        private readonly IHttpClientFactory _http;
        private readonly IConfiguration _conf;
        private readonly IHostEnvironment _env;
        private readonly IHashService _comunes;

        public UserController(IHttpClientFactory http, IConfiguration conf, IHostEnvironment env, IHashService comunes)
        {
            _http = http;
            _conf = conf;
            _env = env;
            _comunes = comunes;
        }

        [HttpGet]
        [Route("Profile")]
        public IActionResult Profile()
        {
            // Obtener el consecutivo del usuario desde la sesión
            var consecutivo = HttpContext.Session.GetString("UserConsecutive");

            if (string.IsNullOrEmpty(consecutivo))
            {
                return RedirectToAction("Login", "Login");
            }

            try
            {
                using (var client = _http.CreateClient())
                {
                    // Llamar a la API para obtener las recetas favoritas del usuario
                    string url = _conf.GetSection("Variables:RutaApi").Value + "Profile/GetFavoriteRecipes/" + consecutivo;

                    var response = client.GetAsync(url).Result;

                    if (response.IsSuccessStatusCode)
                    {
                        var result = response.Content.ReadFromJsonAsync<Respuesta>().Result;

                        if (result != null && result.Codigo == 0)
                        {
                            var favoriteRecipes = JsonSerializer.Deserialize<List<FavoriteRecipeResponse>>(result.Contenido.ToString());
                            ViewBag.FavoriteRecipes = favoriteRecipes;
                            return View();
                        }
                        else
                        {
                            ViewBag.Mensaje = result?.Mensaje ?? "No se encontraron recetas favoritas.";
                          
                        }
                    }
                    else
                    {
                        ViewBag.Mensaje = "Error al obtener las recetas favoritas desde el servidor.";
                    
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = $"Error en la solicitud: {ex.Message}";
            }

            // Retornar la vista con los datos del usuario
            return View();
        }




        [HttpGet]
        public IActionResult EditProfile()
        
        {

            // Obtener el consecutivo del usuario desde la sesión
            var consecutivo = HttpContext.Session.GetString("UserConsecutive");

            if (string.IsNullOrEmpty(consecutivo))
            {
                return RedirectToAction("Login", "Login");
            }


            using (var client = _http.CreateClient())
            {
                string url = _conf.GetSection("Variables:RutaApi").Value + "Profile/CheckUser?Consecutivo=" + consecutivo;

                var response = client.GetAsync(url).Result;
                var result = response.Content.ReadFromJsonAsync<Respuesta>().Result;

                if (result != null && result.Codigo == 0)
                {
                    var datosContenido = JsonSerializer.Deserialize<Users>((JsonElement)result.Contenido!);
                    return View(datosContenido);
                }

                return View(new Users());
            }
        }

        [HttpPost]
        public IActionResult EditProfile(EditProfile model)
        {
            model.Id = long.Parse(HttpContext.Session.GetString("UserConsecutive")!);

            using (var client = _http.CreateClient())
            {
                string url = _conf.GetSection("Variables:RutaApi").Value + "Profile/UpdateProfile";

                JsonContent datos = JsonContent.Create(model);

                
                var response = client.PutAsync(url, datos).Result;
                var result = response.Content.ReadFromJsonAsync<Respuesta>().Result;

                if (result != null && result.Codigo == 0)
                {
                    HttpContext.Session.SetString("UserName", model.Name);
                    HttpContext.Session.SetString("UserEmail", model.Email);

                    return RedirectToAction("Profile");
                }
                else
                {
                    ViewBag.Mensaje = result!.Mensaje;
                    return View();
                }
            }
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }


        [HttpPost]
        public IActionResult ChangePassword(ChangePassword model)
        {
            model.Password = _comunes.Encrypt(model.Password);
            model.ConfirmPassword = _comunes.Encrypt(model.ConfirmPassword);

            if (model.Password != model.ConfirmPassword)
            {
                ViewBag.Mensaje = "Your password confirmation does not match";
                return View();
            }

            model.Id = long.Parse(HttpContext.Session.GetString("UserConsecutive")!);

            using (var client = _http.CreateClient())
            {
                string url = _conf.GetSection("Variables:RutaApi").Value + "Profile/ChangePass";

                JsonContent datos = JsonContent.Create(model);

                
                var response = client.PutAsync(url, datos).Result;
                var result = response.Content.ReadFromJsonAsync<Respuesta>().Result;

                if (result != null && result.Codigo == 0)
                {
                    ViewBag.Mensaje = "Password changed!";
                    return View();
                }
                else
                {
                    ViewBag.Mensaje = result!.Mensaje;
                    return View();
                }
            }
        }



    }
}

TastyNet/TastyNet/Views/Shared/_Layout.cshtml
@{
    var nombreUsuario = "Guest";

    var rolUsuario = "0";

    @if (Context.Session.GetString("UserName") != null)
    {
        nombreUsuario = @Context.Session.GetString("UserName");
    }


    @if (Context.Session.GetString("UserRole") != null)
    {
        rolUsuario = @Context.Session.GetString("UserRole");
    }

}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Tasty Nest</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Favicons -->
    <link href="img/favicon.png" rel="icon">
    <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Cardo:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/lib/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/lib/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/lib/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/lib/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="~/css/main.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: PhotoFolio
    * Template URL: https://bootstrapmade.com/photofolio-bootstrap-photography-website-template/
    * Updated: Aug 07 2024 with Bootstrap v5.3.3
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body class="index-page">

    <header id="header" class="header d-flex align-items-center sticky-top">
        <div class="container-fluid position-relative d-flex align-items-center justify-content-between">

            <a href="@Url.Action("Index","Home")" class="logo d-flex align-items-center me-auto me-xl-0">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="assets/img/logo.png" alt=""> -->
                <i class="bi bi-cup-straw"></i>
                <h1 class="sitename">TastyNest</h1>
            </a>

            <nav id="navmenu" class="navmenu">
                <ul>
                    <li><a href="@Url.Action("Index","Home")" class="active">Home</a></li>

                    @if (Context.Session.GetString("UserRole") == "1")
                    {
                        <!-- Opciones para Admin -->
                        <li><a href="@Url.Action("Index", "Admin")">Administrator</a></li>
                    }

                    @if (Context.Session.GetString("UserRole") == "2")
                    {
                        <!-- Opciones para cliente -->
                        <li class="dropdown">
                            <a href="#"><span>Recipes</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                            <ul>

                                <li class="dropdown">
                                    <a href="#"><span>Quick & Easy</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                                    <ul>
                                        <li><a href="@Url.Action("ThirtyMinuteMeals", "Recipes")">30-Minute Meals</a></li>
                                        <li><a href="@Url.Action("FiveIngredientsOrLess", "Recipes")">5 Ingredients or Less</a></li>
                                        <li><a href="@Url.Action("OnePotDishes", "Recipes")">One-Pot Dishes</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#"><span>Comfort Food</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                                    <ul>
                                        <li><a href="@Url.Action("CasserolesAndBakes", "Recipes")">Casseroles & Bakes</a></li>
                                        <li><a href="@Url.Action("SoupsAndStews", "Recipes")">Soups & Stews</a></li>
                                        <li><a href="@Url.Action("FamilyFavorites", "Recipes")">Family Favorites</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#"><span>World Flavors</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                                    <ul>
                                        <li><a href="@Url.Action("Italian", "Recipes")">Italian</a></li>
                                        <li><a href="@Url.Action("Asian", "Recipes")">Asian</a></li>
                                        <li><a href="@Url.Action("Mexican", "Recipes")">Mexican</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#"><span>Cakes & Cupcakes</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                                    <ul>
                                        <li><a href="@Url.Action("CakesAndCupcakes", "Recipes")">Cakes & Cupcakes</a></li>
                                        <li><a href="@Url.Action("CookiesAndBars", "Recipes")">Cookies & Bars</a></li>
                                        <li><a href="@Url.Action("PiesAndDesserts", "Recipes")">Pies & Desserts</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#"><span>Healthy Choices</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                                    <ul>
                                        <li><a href="@Url.Action("LowCarb", "Recipes")">Low-Carb</a></li>
                                        <li><a href="@Url.Action("VeganAndVegetarian", "Recipes")">Vegan & Vegetarian</a></li>
                                        <li><a href="@Url.Action("GlutenFree", "Recipes")">Gluten-Free</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#"><span>Weekend Meals</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                                    <ul>
                                        <li><a href="@Url.Action("RoastsAndGrills", "Recipes")">Roasts & Grills</a></li>
                                        <li><a href="@Url.Action("BrunchFavorites", "Recipes")">Brunch Favorites</a></li>
                                        <li><a href="@Url.Action("PartyPlates", "Recipes")">Party Plates</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li><a href="@Url.Action("Favorites", "Home")">Favorites</a></li>
                    }

                    
             
                </ul>
                <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
            </nav>

            @if (Context.Session.GetString("UserName") != null)
            {
                <!-- Opciones comunes para todos los usuarios autenticados -->
                <li class="dropdown position-relative">
                    <a href="#" class="d-flex align-items-center dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <span>@nombreUsuario</span>
                        <i class="bi bi-chevron-down ms-2"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="@Url.Action("Profile", "User")">Profile</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Logout", "Login")">Logout</a></li>
                    </ul>
                </li>



            }
            else
            {
                <div class="header-social-links">
                    <ul class="d-flex align-items-center list-unstyled">
                        <li><a href="@Url.Action("Login", "Login")" class="active">Login</a></li>
                        <li class="ms-3"><a href="@Url.Action("Register", "Login")" class="active">Register</a></li>
                    </ul>
                </div>
            }

        </div>
    </header>

    <main class="main">
        @if (IsSectionDefined("MainContent"))
        {
            @RenderSection("MainContent", required: false)
        }
        else
        {
            <!-- Optional: Default content if no section is defined -->
            <div class="container">
                <h2 class="text-center my-5">Welcome to Tasty Nest!</h2>
            </div>
        }
    </main>


    <footer id="footer" class="footer">

        <div class="container">
            <div class="copyright text-center ">
                <p>© <span>Copyright</span> <strong class="px-1 sitename">TastyNest</strong> <span>All Rights Reserved</span></p>
            </div>
            <div class="social-links d-flex justify-content-center">
                <a href=""><i class="bi bi-twitter-x"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-pinterest"></i></a>
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you've purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>

    </footer>

    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Preloader -->
    <div id="preloader">
        <div class="line"></div>
    </div>

    <!-- Vendor JS Files -->
    <script src="~/lib/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- <script src="~/lib/vendor/php-email-form/validate.js"></script> -->
    <script src="~/lib/vendor/aos/aos.js"></script>
    <script src="~/lib/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/lib/vendor/swiper/swiper-bundle.min.js"></script>

    <!-- Main JS File -->
    <script src="~/js/main.js"></script>
    <script src="~/js/favorites.js"></script>


</body>

</html>

TastyNet/TastyNet/Views/Shared/_LayoutDash.cshtml
@{
    var nombreUsuario = "Guest";

    var rolUsuario = "0";

    @if (Context.Session.GetString("UserName") != null)
    {
        nombreUsuario = @Context.Session.GetString("UserName");
    }


    @if (Context.Session.GetString("UserRole") != null)
    {
        rolUsuario = @Context.Session.GetString("UserRole");
    }

}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Tasty Nest</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Favicons -->
    <link href="img/favicon.png" rel="icon">
    <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Cardo:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/lib/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/lib/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/lib/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/lib/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    

    <!-- Main CSS File -->
    <link href="~/css/main.css" rel="stylesheet">
    <link  href="~/css/styles.css" rel="stylesheet">


    <!-- =======================================================
    * Template Name: PhotoFolio
    * Template URL: https://bootstrapmade.com/photofolio-bootstrap-photography-website-template/
    * Updated: Aug 07 2024 with Bootstrap v5.3.3
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body class="index-page">

    <header id="header" class="header d-flex align-items-center sticky-top">
        <div class="container-fluid position-relative d-flex align-items-center justify-content-between">

            <a href="@Url.Action("Index","Home")" class="logo d-flex align-items-center me-auto me-xl-0">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="assets/img/logo.png" alt=""> -->
                <i class="bi bi-cup-straw"></i>
                <h1 class="sitename">TastyNest</h1>
            </a>

            <nav id="navmenu" class="navmenu">
                <ul>
                    <li><a href="@Url.Action("Index","Home")" class="active">Home<br></a></li>

                    @if (Context.Session.GetString("UserRole") == "1")
                    {
                        <!-- Opciones para Admin -->
                        <li><a href="@Url.Action("Index", "Admin")">Administrator</a></li>
                    }

                    @if (Context.Session.GetString("UserRole") == "2")
                    {
                        <!-- Opciones para Cliente -->
                    }

                    <li class="dropdown">
                        <a href="#"><span>Recipes</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                        <ul>

                            <li class="dropdown">
                                <a href="#"><span>Quick & Easy</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                                <ul>
                                    <li><a href="@Url.Action("ThirtyMinuteMeals", "Recipes")">30-Minute Meals</a></li>
                                    <li><a href="@Url.Action("FiveIngredientsOrLess", "Recipes")">5 Ingredients or Less</a></li>
                                    <li><a href="@Url.Action("OnePotDishes", "Recipes")">One-Pot Dishes</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#"><span>Comfort Food</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                                <ul>
                                    <li><a href="@Url.Action("CasserolesAndBakes", "Recipes")">Casseroles & Bakes</a></li>
                                    <li><a href="@Url.Action("SoupsAndStews", "Recipes")">Soups & Stews</a></li>
                                    <li><a href="@Url.Action("FamilyFavorites", "Recipes")">Family Favorites</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#"><span>World Flavors</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                                <ul>
                                    <li><a href="@Url.Action("Italian", "Recipes")">Italian</a></li>
                                    <li><a href="@Url.Action("Asian", "Recipes")">Asian</a></li>
                                    <li><a href="@Url.Action("Mexican", "Recipes")">Mexican</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#"><span>Cakes & Cupcakes</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                                <ul>
                                    <li><a href="@Url.Action("CakesAndCupcakes", "Recipes")">Cakes & Cupcakes</a></li>
                                    <li><a href="@Url.Action("CookiesAndBars", "Recipes")">Cookies & Bars</a></li>
                                    <li><a href="@Url.Action("PiesAndDesserts", "Recipes")">Pies & Desserts</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#"><span>Healthy Choices</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                                <ul>
                                    <li><a href="@Url.Action("LowCarb", "Recipes")">Low-Carb</a></li>
                                    <li><a href="@Url.Action("VeganAndVegetarian", "Recipes")">Vegan & Vegetarian</a></li>
                                    <li><a href="@Url.Action("GlutenFree", "Recipes")">Gluten-Free</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#"><span>Weekend Meals</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                                <ul>
                                    <li><a href="@Url.Action("RoastsAndGrills", "Recipes")">Roasts & Grills</a></li>
                                    <li><a href="@Url.Action("BrunchFavorites", "Recipes")">Brunch Favorites</a></li>
                                    <li><a href="@Url.Action("PartyPlates", "Recipes")">Party Plates</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
                <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
            </nav>

            @if (Context.Session.GetString("UserName") != null)
            {
                <!-- Opciones comunes para todos los usuarios autenticados -->
                <li class="dropdown position-relative">
                    <a href="#" class="d-flex align-items-center dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <span>@nombreUsuario</span>
                        <i class="bi bi-chevron-down ms-2"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="@Url.Action("Profile", "User")">Profile</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Logout", "Login")">Logout</a></li>
                    </ul>
                </li>



            }
            else
            {
                <div class="header-social-links">
                    <ul class="d-flex align-items-center list-unstyled">
                        <li><a href="@Url.Action("Login", "Login")" class="active">Login</a></li>
                        <li class="ms-3"><a href="@Url.Action("Register", "Login")" class="active">Register</a></li>
                    </ul>
                </div>
            }

        </div>
    </header>

    <main class="main">

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

    </main>

    <footer id="footer" class="footer">

        <div class="container">
            <div class="copyright text-center ">
                <p>© <span>Copyright</span> <strong class="px-1 sitename">TastyNest</strong> <span>All Rights Reserved</span></p>
            </div>
            <div class="social-links d-flex justify-content-center">
                <a href=""><i class="bi bi-twitter-x"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-pinterest"></i></a>
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you've purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>

    </footer>

    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Preloader -->
    <div id="preloader">
        <div class="line"></div>
    </div>

    <!-- Vendor JS Files -->
    <script src="~/lib/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/vendor/aos/aos.js"></script>
    <script src="~/lib/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/lib/vendor/swiper/swiper-bundle.min.js"></script>

    <!-- Main JS File -->
    <script src="~/js/main.js"></script>
</body>

</html>